version: 2
jobs:
  build:
    working_directory: ~/AndroidDockerApplication
    context: SonarCloud
    docker:
      - image: circleci/android:api-30
      - image: 'circleci/openjdk:11-jdk'
    environment:
      JAVA_HOME: C:\Program Files\Java\jdk-15.0.1
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube"
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
